version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    volumes:
      - ./apps/api:/app
      - ./data:/data
    environment:
      - DATABASE_URL=sqlite:////data/recipes.db
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - api

  # optional postgres service if you want to switch
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: recipehub
      POSTGRES_PASSWORD: recipehub
      POSTGRES_DB: recipehub
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
