version: "3.9"

services:
api:
build:
context: .
dockerfile: docker/Dockerfile.api
container_name: recipehub_api
ports:
- "8000:8000"
volumes:
- ./apps/servers:/app
- ./data:/data
environment:
- PYTHONUNBUFFERED=1
depends_on:
- db

web:
build:
context: .
dockerfile: docker/Dockerfile.web
container_name: recipehub_web
ports:
- "5173:80"
depends_on:
- api

db:
image: postgres:15
container_name: recipehub_db
restart: always
environment:
POSTGRES_USER=recipehub
POSTGRES_PASSWORD=recipehub123
POSTGRES_DB=recipehub_db
ports:
- "5432:5432"
volumes:
- postgres_data:/var/lib/postgresql/data

volumes:
postgres_data:
